culture_dict = {'What famous theater in London is known for its iconic "Hamlet" performances?': 'The Globe Theatre',
                'Which Asian country is known as the "Land of the Rising Sun"?': 'Japan',
                'In what country did the Renaissance period begin?': 'Italy',
                'What is the traditional dance of Hawaii?': 'Hula',
                'Which ancient civilization built the pyramids in Egypt?': 'Ancient Egyptians',
                'Who painted the Mona Lisa?': 'Leonardo da Vinci',
                'What is the national sport of Japan?': 'Sumo wrestling',
                'In which country did the tango dance originate?': 'Argentina',
                'What is the traditional clothing of Scotland?': 'Kilts',
                'Who wrote the play "Romeo and Juliet"?': 'William Shakespeare',
                'What is the main language spoken in Brazil?': 'Portuguese',
                'Which island nation is famous for its Maori culture and haka dance?': 'New Zealand',
                'What is the name of the Mexican holiday celebrating the Day of the Dead?': 'Dia de los Muertos',
                'Who wrote "War and Peace" and "Anna Karenina"?': 'Leo Tolstoy',
                'What is the national flower of Japan?': 'Cherry blossom',
                'What is the traditional clothing of India for women?': 'Sari',
                'What is the national dish of Spain?': 'Paella',
                'What style of music was popularized in Jamaica in the 1960s and influenced reggae?': 'Ska',
                'Who painted "The Starry Night" and "Sunflowers"?': 'Vincent van Gogh',
                'What is the traditional music of the Australian Aboriginal people called?': 'Didgeridoo',
                'What is the traditional music of Ireland often played with fiddles and flutes?': 'Irish traditional music',
                'Which famous artist is known for creating "The Persistence of Memory" with melting clocks?': 'Salvador Dalí',
                'In which country did the famous playwright Anton Chekhov originate?': 'Russia',
                'Who wrote "1984" and "Animal Farm"?': 'George Orwell',
                'Who directed the movie "Titanic" and "Avatar"?': 'James Cameron',
                'Who is known as the "Father of Modern Physics" and developed the theory of relativity?': 'Albert Einstein',
                'What is the traditional Korean dish of fermented vegetables, primarily napa cabbage?': 'Kimchi',
                'In which country did the famous playwright Henrik Ibsen originate?': 'Norway',
                'What is the traditional percussion instrument of Cuba?': 'Bongos',
                'Which ancient civilization built the city of Machu Picchu?': 'The Inca civilization',
                'What custom involves shaking hands to greet someone?': 'Handshaking',
                'In Japan, what is the customary way to show respect when receiving a gift?': 'Bowing',
                'Which culture traditionally exchanges red envelopes filled with money during the Lunar New Year?': 'Chinese',
                'In Hindu weddings, what is the custom of applying red powder or paste to the bride\'s forehead called?': 'Sindoor',
                'In which country is it customary to kiss both cheeks as a greeting?': 'France',
                'What is the traditional Chinese art of arranging furniture and objects to promote harmony called?': 'Feng Shui',
                'What\'s the custom of eating 12 grapes at the stroke of midnight on New Year\'s Eve in Spain known as?': 'The 12 Grapes of Luck',
                'In Hindu customs, what do the groom and bride exchange during the wedding ceremony?': 'Garlands of flowers',
                'Which African country is known for its traditional custom of lip plates worn by women?': 'Ethiopia',
                'What\'s the custom of throwing rice at newlyweds as they leave the wedding ceremony called?': 'Rice tossing',
                'What\'s the traditional Indian custom of applying decorative designs on the hands and feet with henna called?': 'Mehdi',
                'What is the traditional Japanese tea ceremony called?': 'Chanoyu',
                'What is the custom of lighting candles on a menorah during Hanukkah in Jewish traditions?': 'Menorah lighting',
                'In Thailand, what is the custom of pressing one\'s palms together as a sign of respect or greeting called?': 'Wai',
                'In ancient Rome, what custom marked the end of a gladiatorial match, allowing the audience to decide the fate of the defeated gladiator?': 'Thumbs up or thumbs down',
                'What is the traditional custom of drinking tea with a small snack in the late afternoon in England?': 'Afternoon tea',
                'What is the custom of placing small stones on a grave marker to show that someone has visited in Jewish traditions?': 'Leaving a pebble',
                'What is the traditional Scottish custom of a social gathering with music, dance, and storytelling called?': 'Ceilidh',
                'What is the traditional Japanese custom of wrapping gifts with decorative paper and folding techniques?': 'Origata',
                'What is the custom of celebrating the arrival of a new year with a countdown and fireworks at midnight?': 'New Year\'s Eve celebration',
                'What is the traditional Hawaiian custom of presenting a garland of flowers, often as a welcome gesture?': 'Lei',
                'Which country is famous for the tradition of Oktoberfest?': 'Germany',
                'What is the traditional dress of Japan?': 'Kimono',
                'Which Native American tribe is known for their longhouses and totem poles?': 'Haida',
                'What is the national flower of Ireland?': 'Shamrock',
                'Which famous architect designed the Sydney Opera House?': 'Jørn Utzon',
                'Which African country is known as the "Land of a Thousand Hills"?': 'Rwanda',
                'Who wrote the epic poem "The Iliad"?': 'Homer',
                'In which European city is the Acropolis located?': 'Athens, Greece',
                'Which language is spoken in the most countries worldwide?': 'English',
                'What is the famous historic site in England associated with the legend of King Arthur?': 'Tintagel Castle',
                'What is the official language of Iran?': 'Farsi',
                'In which country is the historic city of Prague located?': 'Czech Republic',
                'Which country is known for its tradition of "Fika," a coffee break with pastries?': 'Sweden',
                'What is the national flower of the Netherlands?': 'Tulip',
                'Which Native American tribe is famous for their skill in pottery and jewelry making?': 'Hopi',
                'Who was the first woman to fly solo across the Atlantic Ocean?': 'Amelia Earhart',
                'Which African country is known as the "Cradle of Humankind" due to important fossil discoveries?': 'South Africa',
                'What is the traditional headgear worn by men in Saudi Arabia and other Gulf countries?': 'Ghutrah or Keffiyeh'}

culture_ans_dict = {'The Globe Theatre': ['The Globe Theatre', 'The Royal Opera House', 'The Apollo Victoria Theatre',
                                          'The Barbican Centre'],
                    'Japan': ['Japan', 'China', 'India', 'Thailand'],
                    'Italy': ['Italy', 'Greece', 'France', 'Egypt'],
                    'Hula': ['Hula', 'Tap dancing', 'Moonwalking', 'Belly dancing'],
                    'Ancient Egyptians': ['Ancient Egyptians', 'Ancient Romans', 'Ancient Greeks', 'Ancient Mayans'],
                    'Leonardo da Vinci': ['Leonardo da Vinci', 'Pablo Picasso', 'Vincent van Gogh',
                                          'Leonardo DiCaprio'],
                    'Sumo wrestling': ['Sumo wrestling', 'Extreme ironing', 'Judo', 'Chess'],
                    'Argentina': ['Argentina', 'Greenland', 'Spain', 'Cuba'],
                    'Kilts': ['Kilts', 'Tropical Hawaiian shirts', 'Tuxedos', 'Leather bikinis'],
                    'William Shakespeare': ['William Shakespeare', 'Dr. Seuss', 'J.K. Rowling', 'Shakespeare Jr.'],
                    'Portuguese': ['Portuguese', 'Spanish', 'English', 'French'],
                    'New Zealand': ['New Zealand', 'Fiji', 'Tonga', 'Solomon Islands'],
                    'Dia de los Muertos': ['Dia de los Muertos', 'Cinco de Mayo', 'Día de la Raza',
                                           'Día de los Angelitos'],
                    'Leo Tolstoy': ['Leo Tolstoy', 'Charles Dickens', 'Mark Twain', 'Jane Austen'],
                    'Cherry blossom': ['Cherry blossom', 'Sunflower', 'Rose', 'Daisy'],
                    'Sari': ['Sari', 'Kimono', 'Tuxedo', 'Cowboy hat'],
                    'Paella': ['Paella', 'Hamburger', 'Sushi', 'Tacos'],
                    'Ska': ['Ska', 'Opera', 'Heavy metal', 'Polka'],
                    'Vincent van Gogh': ['Vincent van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Jackson Pollock'],
                    'Didgeridoo': ['Didgeridoo', 'Reggae', 'Hip-hop', 'Jazz'],
                    'Irish traditional music': ['Irish traditional music', 'Heavy metal', 'Country', 'Bagpipes'],
                    'Salvador Dalí': ['Salvador Dalí', 'Michelangelo', 'Leonardo da Vinci', 'Pablo Picasso'],
                    'Russia': ['Russia', 'France', 'Italy', 'China'],
                    'George Orwell': ['George Orwell', 'J.K. Rowling', 'Charles Dickens', 'Mark Twain'],
                    'James Cameron': ['James Cameron', 'Steven Spielberg', 'Quentin Tarantino', ' Martin Scorsese'],
                    'Albert Einstein': ['Albert Einstein', 'Isaac Newton', 'Marie Curie', 'Thomas Edison'],
                    'Kimchi': ['Kimchi', 'Sushi', 'Dim Sum', 'Pad Thai'],
                    'Norway': ['Norway', 'Sweden', 'Denmark', 'Finland'],
                    'Bongos': ['Bongos', 'Bagpipes', 'Flute', 'Trombone'],
                    'The Inca civilization': ['The Inca civilization', 'The Aztec civilization', 'The Mayan civilization', 'The Ancient Egyptians'],
                    'Handshaking': ['Handshaking', 'Fist bumping', 'High-fiving', 'Hugging'],
                    'Bowing': ['Bowing', 'Dancing', 'Clapping', 'Doing a cartwheel'],
                    'Chinese': ['Chinese', 'Inuit', 'Japanese', 'Korean'],
                    'Sindoor': ['Sindoor', 'Chocolate frosting', 'Sari', 'Baraat'],
                    'France': ['France', 'Spain', 'Canada', 'Mexico'],
                    'Feng Shui': ['Feng Shui', 'Jenga', 'He', 'Kung Fu'],
                    'The 12 Grapes of Luck': ['The 12 Grapes of Luck', 'Grape juggling', 'Grape stomping', 'Grape sacrifice'],
                    'Garlands of flowers': ['Garlands of flowers', 'Rings', 'Good Luck Charms', 'Twigs'],
                    'Ethiopia': ['Ethiopia', 'Tanzania', 'Chad', 'Ghana'],
                    'Rice tossing': ['Rice tossing', 'Rice rain dance', 'Rice Throw', 'Rice Wish'],
                    'Mehdi': ['Mehdi', 'Achkan', 'Bindi', 'Haldi'],
                    'Chanoyu': ['Chanoyu', 'Bancha', 'Hojicha', 'Koicha'],
                    'Menorah lighting': ['Menorah lighting', 'Candelabra lighting', 'Hanukkah lighting', 'Menorah'],
                    'Wai': ['Wai'],
                    'Thumbs up or thumbs down': ['Thumbs up or thumbs down', 'Nod up or Nod down', 'Open palm or Closed Fist', 'One finger up or Two fingers up'],
                    'Afternoon tea': ['Afternoon tea'],
                    'Leaving a pebble': ['Leaving a pebble'],
                    'Ceilidh': ['Ceilidh'],
                    'Origata': ['Origata'],
                    'New Year\'s Eve celebration': ['New Year\'s Eve celebration'],
                    'Lei': ['Lei'],
                    'Germany': ['Germany'],
                    'Kimono': ['Kimono'],
                    'Haida': ['Haida'],
                    'Shamrock': ['Shamrock'],
                    'Jørn Utzon': ['Jørn Utzon'],
                    'Rwanda': ['Rwanda'],
                    'Homer': ['Homer'],
                    'Athens, Greece': ['Athens, Greece'],
                    'English': ['English'],
                    'Tintagel Castle' : ['Tintagel Castle'],
                    'Farsi':['Farsi'],
                    'Czech Republic': ['Czech Republic'],
                    'Sweden': ['Sweden'],
                    'Tulip': ['Tulip'],
                    'Hopi' : ['Hopi'],
                    'Amelia Earhart': ['Amelia Earhart'],
                    'South Africa': ['South Africa'],
                    'Ghutrah or Keffiyeh': ['Ghutrah or Keffiyeh']
                    }
