relation_dict = {'What is the traditional gift for a 50th wedding anniversary?': 'Gold',
                 'Which hormone is often referred to as the "love hormone"?': 'Oxytocin',
                 'What is the average duration of engagement in the United States before marriage?': '13.6 months',
                 'What is the term for a romantic relationship between people of significant age difference?': 'May-December Relationship',
                 "What's the most common reason for divorce in the United States?": 'Irreconcilable Differences',
                 'What percentage of marriages in the U.S. are estimated to end in divorce?': '40-50%',
                 'What is the psychological term for the phenomenon of feeling closer to someone after sharing personal information with them?': 'Self-Disclosure',
                 'In which country did the tradition of wearing a wedding ring on the fourth finger of the left hand originate?': 'Egypt',
                 "What's the term for the phenomenon where people in a relationship begin to mimic each other's behaviors and mannerisms?": 'Mirroring',
                 "What is the most common day for breakups, often referred to as 'Breakup Day'?": 'The day before Valentine\'s Day',
                 'Who is often credited with creating the concept of attachment styles in romantic relationships?': 'John Bowlby',
                 "What's the term for the emotional distress that follows the end of a romantic relationship?": 'Heartbreak',
                 'Who is known as the "Father of Modern Psychoanalysis" and wrote extensively on the Oedipus complex?': 'Sigmund Freud',
                 'In a relationship, what does the acronym "SO" stand for?': 'Significant Other',
                 "What's the term for the act of ending a romantic relationship by ceasing all communication and contact?": 'Ghosting',
                 'What is the legal term for a marriage that is annulled and treated as if it never existed?': 'Nullity',
                 "What's the term for the act of ending a romantic relationship by gradually reducing contact and interaction?": 'Slow Fade',
                 "What's the term for a strong and often irrational fear of being alone?": 'Autophobia',
                 'What is the psychological term for the idea that we tend to be attracted to people who are similar to us?': 'Homophily',
                 'Who authored the book "The 5 Love Languages"?': 'Gary Chapman',
                 'Which of the below animals does not form monogamous pair bonds?': 'Gorillas',
                 'In a relationship, what does the term "DTR" stand for?': 'Define the Relationship',
                 'What is the initial period of intense love and affection in a relationship?': 'Honeymoon Phase',
                 'What percentage of marriages are estimated to experience infidelity at some point?': '20-25%',
                 'What is the term for a period of restlessness or dissatisfaction in a long-term relationship, typically occurring around the seventh year?': '7-Year Itch',
                 'Who wrote the book "Men Are from Mars, Women Are from Venus"?': 'John Gray',
                 "What's the term for the practice of maintaining a romantic relationship without the intention of long-term commitment?": 'Casual Dating',
                 "Your niece's child is what relation to you?": 'Great Niece/Nephew',
                 'What is the term for the child of your first cousin?': 'Second Cousin',
                 'What is the relationship between your son\'s daughter and you?': 'Granddaughter',
                 'What is the relationship between your father’s brother’s nephew’s cousin’s mother?': 'Aunt',
                 'How many generations are there between you and your great-grandparents?': 'Three',
                 'What is the term for the child of your first cousin once removed?': 'First Cousin Twice Removed',
                 'What is the relationship between your grandfather\'s daughter and you?': 'Not Enough Information',
                 'How many aunts and uncles do you have if your parents each have one sibling?': 'Two',
                 'Which ancestors do you share directly with your second cousins?': 'Great Grandparents',
                 'What relation could you not be to your uncle’s uncle’s brother’s grandson’s mother?': 'Yourself',
                 'In the TV show "Friends," what was the name of Ross and Monica\'s dog when they were kids?': 'Chi-Chi',
                 'What percentage of friendships are believed to be formed within a 20-mile radius of your home?': '50%',
                 'Who coined the phrase "A friend in need is a friend indeed"?': 'Ennius',
                 'What is the name of the neighbor who lives next door to the Simpsons in the TV show "The Simpsons"?': 'Ned Flanders',
                 'In psychology, what is the term for the phenomenon where people become friends with those they see frequently?': 'Propinquity',
                 'What is the traditional gift for a 20th wedding anniversary?': 'China',
                 'Who is the author of the book "The Friendship Factor"?': 'Alan Loy McGinnis',
                 'In Greek mythology, who was (at minimum) the best friend of Achilles?': 'Patroclus',
                 'Who wrote the play "The Comedy of Errors," which revolves around mistaken identity and friendship?': 'William Shakespeare',
                 'What is the term for a friend who shares your interests and hobbies?': 'Kindred Spirit',
                 'What TV show featured a group of friends who lived in an apartment building called "The Regal Beagle"?': "Three’s Company",
                 'What is the term for a friend who shares your same birthdate?': 'Birthday Twin',
                 "What is the term for a friend who is brutally honest with you, even if it hurts?": 'Tough Love Friend',
                 'Who wrote the book "The Art of Friendship"?': 'Kim Leary'
                 }

relation_ans_dict = {'Gold': ['Gold', 'Silver', 'Diamond', 'China'],
                     'Oxytocin': ['Oxytocin', 'Serotonin', 'Dopamine', 'Endorphins'],
                     '13.6 months': ['13.6 months', '15.2 months', '6.5 months', '10.7 months'],
                     'May-December Relationship': ['May-December Relationship', 'Spring-Winter Relationship',
                                                   'Janeway Relationship', 'Cup Bearer Relationship'],
                     'Irreconcilable Differences': ['Irreconcilable Differences', 'Money', 'Infidelity', 'In Laws'],
                     '40-50%': ['40-50%', '30-40%', '50-60%', '60-70%'],
                     'Self-Disclosure': ['Self-Disclosure', 'Emotional Intimacy', 'Ego Sharing', 'Social Connection'],
                     'Egypt': ['Egypt', 'Great Britain', 'Italy', 'Turkey'],
                     'Mirroring': ['Mirroring', 'Reflecting', 'Codependency', 'Twinning'],
                     "The day before Valentine's Day": ["The day before Valentine's Day",
                                                        " The day after Valentine's Day", "New Year’s Day",
                                                        "The day after Christmas"],
                     'John Bowlby': ['John Bowlby', 'Robert Sternberg', ' Richard J. Calabrese', ' Susan Hendrick'],
                     'Heartbreak': ['Heartbreak', 'Depression', 'Lovelorn', 'Jilted'],
                     'Sigmund Freud': ['Sigmund Freud', 'Sophocles', 'Shakespeare', 'Carl Jung'],
                     'Significant Other': ['Significant Other', 'Speciall Offering', 'Social Order', 'Spousal Odor'],
                     'Ghosting': ['Ghosting', 'No Contact', 'Irish Exit', 'Breadcrumbing'],
                     'Nullity': ['Nullity', 'Voidance', 'Mistake', 'Mulligan'],
                     'Slow Fade': ['Slow Fade', 'Dissolve', 'Vanishing Act', 'Evaporation'],
                     'Autophobia': ['Autophobia', 'Scotophobia', 'Mazeophobia', 'Philophobia'],
                     'Homophily': ['Homophily', 'Oedipus Complex', 'Narcissus Complex', 'Heterophily'],
                     'Gary Chapman': ['Gary Chapman', 'John Trent', 'E.L. James', 'John Green'],
                     'Gorillas': ['Gorillas', 'Bald Eagles', 'Swans', 'Seahorses'],
                     'Define the Relationship': ['Define the Relationship', 'Down to Ride', 'Drop the Reverse',
                                                 'Ditch the Relationship'],
                     'Honeymoon Phase': ['Honeymoon Phase', 'Newly Wed Phase', 'Lovesickness', 'The Illusion'],
                     '20-25%': ['20-25%', '15-25%', '30-35%', '35-40%'],
                     '7-Year Itch': ['7-Year Itch', '7th Inning Stretch', 'Mid-Relationship Crisis',
                                     'The Wandering 7s'],
                     'John Gray': ['John Gray', 'Josh Green', 'Judith Eve', 'David Barash'],
                     'Casual Dating': ['Casual Dating', 'Semi-Formal Dating', 'Leisure Dating', 'Ballroom Dating'],
                     'Great Niece/Nephew': ['Great Niece/Nephew', 'Niece/Nephew', 'Good Niece/Nephew',
                                            'Grand Niece/Nephew'],
                     'Second Cousin': ['Second Cousin', 'Third Cousin', 'Diagonal Cousin',
                                       'Second Cousin Once Removed'],
                     'Granddaughter': ['Granddaughter', 'Grandson', 'Niece', 'Grandmother'],
                     'Aunt': ['Aunt', 'Cousin', 'Grandmother', 'Sister'],
                     'Three': ['Three', 'Two', 'Four', 'Zero'],
                     'First Cousin Twice Removed': ['First Cousin Twice Removed', 'Second Cousin Once Removed',
                                                    'Second Cousin Twice Removed', 'First Cousin Three Times Removed'],
                     'Not Enough Information': ['Not Enough Information', 'Mother', 'Aunt', 'Great Aunt'],
                     'Two': ['Two', 'Four', 'Not Enough Information', 'Zero'],
                     'Great Grandparents': ['Great Grandparents', 'Grandparents', 'Great Great Grandparents',
                                            'Aunts and Uncles'],
                     'Yourself': ['Yourself', 'Child', 'None', 'First Cousin Once Removed'],
                     'Chi-Chi': ['Chi-Chi', 'Cha-Cha', 'Cho-Cho', 'Chu-Chu'],
                     '50%': ['50%', '40%', '30%', '60%'],
                     'Ennius': ['Ennius', 'Caxton', 'Unknown', 'Aesop'],
                     'Ned Flanders': ['Ned Flanders', 'Mr. Burns', 'Milhouse', 'Moe Szyslak'],
                     'Propinquity': ['Propinquity', 'Friends of Convenience', 'Stockholm Friends', 'Entropity'],
                     'China': ['China', 'Turkey', 'Gold', 'Wood'],
                     'Alan Loy McGinnis': ['Alan Loy McGinnis', 'John Wilkes Booth', 'Emily Gould', 'Lucinda Berry'],
                     'Patroclus': ['Patroclus', 'Briseis', 'Hector', 'Chiron'],
                     'William Shakespeare': ['William Shakespeare', 'Cristopher Marlowe', 'Andrew Lloyd Webber',
                                             'John Milton'],
                     'Kindred Spirit': ['Kindred Spirit', 'Twin Friend', 'Mirror Spirit', 'Crossover Friend'],
                     "Three’s Company": ["Three’s Company", "Friends", "How I met Your Mother", "Full House"],
                     'Birthday Twin': ['Birthday Twin', 'Fraternal Friend', 'Star Sign Friend', 'Sorority Twin'],
                     'Tough Love Friend': ['Tough Love Friend', 'Blunt Friend', 'Warden Friend', 'Mother Friend'],
                     'Kim Leary': ['Kim Leary', 'Pablo Picasso', 'Sun Tzu', 'Lydia Denworth']
                     }
